### ISSUE TITLE
Changes to some VOWL2 elements

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/WebVOWL#12]
![vowl2_changes](https://cloud.githubusercontent.com/assets/12000584/9410597/60310e06-4821-11e5-817c-f4bfe15d85d3.png)

### TODO
- [x] Change set operator style
- [x] Add anonymous style
- [x] Multiline equivalent labels
- [x] Change style for anonymous links
- [x] Update CSS styles for SVG export
- [x] Clarify direction of BowArrowLinks: (A: box on set operator)
